#if DEBUG
import SwiftUI

/// This area's screens for the debug router (App/DebugScreens.swift):
/// `-neonScreen <id>` opens one straight from launch, for screenshots.
///
/// `status` is the real screen, reading the server. The `status-fixture…`
/// ids draw the same screen from fixed answers, with no server at all — open
/// them signed out with `-uiTestMode` (which signs the app in with a dummy
/// token and refuses every request):
///
///     xcrun simctl launch <device> com.neonjo.staff -uiTestMode -neonScreen status-fixture
///
/// (add `-app_language ar` for Arabic). Debug builds only.
enum StatusScreens {
    static let ids: [String] = [
        "status", "status-fixture", "status-fixture-ok", "status-fixture-down", "status-fixture-unreachable",
        "status-fixture-loading",
    ]

    @MainActor static func view(_ id: String) -> AnyView? {
        switch id {
        case "status": return debugPushed(StatusRootView())
        case "status-fixture": return debugPushed(StatusRootView(load: { StatusFixtures.attention }))
        case "status-fixture-ok": return debugPushed(StatusRootView(load: { StatusFixtures.healthy }))
        case "status-fixture-down": return debugPushed(StatusRootView(load: { StatusFixtures.tunnelDown }))
        case "status-fixture-unreachable": return debugPushed(StatusRootView(load: { throw APIError.network }))
        case "status-fixture-loading":
            return debugPushed(StatusRootView(load: {
                try await Task.sleep(nanoseconds: 600 * 1_000_000_000)
                return StatusFixtures.healthy
            }))
        default: return nil
        }
    }
}

/// Answers in the server's own words (src/lib/status.ts), as the studio's PC
/// would give them. The addresses are documentation ones (203.0.113.0/24).
enum StatusFixtures {
    private static func row(_ id: String, _ title: String, _ state: StatusState, _ detail: String, _ value: String? = nil) -> StatusRow {
        StatusRow(id: id, title: title, state: state, detail: detail, value: value)
    }

    private static let site = row("site", "The site", .up, "Serving for 3 d 4 h, since Mon, Sep 28 11:02 AM · build kq2Xp9LmT4vB · Node v22.20.0", "3 d 4 h")
    private static let database = row("database", "Database", .up, "Answered in 2 ms · 184 MB · 7 of 100 connections · PostgreSQL 17.6 · newest migration 20261001100000_project_access_code (46 applied)", "2 ms")
    private static let jobs = row("jobs", "Scheduled jobs", .up, "Last run 4 min ago (Thu, Oct 1 3:18 PM), took 2.1 s · expected every 10 minutes", "4 min ago")
    private static let meetings = row("meetings", "Meeting reminders", .up, "Last run 40 s ago (Thu, Oct 1 3:21 PM), took 19 ms · expected every minute", "40 s ago")
    private static let backups = row("backups", "Database backups", .up, "Newest neon-2026-10-01-0300.dump, 12 h 22 min ago, 12 MB · 14 kept", "12 h 22 min ago")
    private static let whatsapp = row("whatsapp", "WhatsApp worker", .up, "Connected as +962790000000 · worker at host.docker.internal:4100", "Connected")
    private static let apns = row("apns", "iPhone push", .up, "Configured · 5 iPhones registered · last 24 h: 31 delivered, 0 failed · the last one 12 min ago went through", "5 iPhones")
    private static let webPush = row("web-push", "Web push", .up, "Keys generated by the platform · 3 browsers subscribed · last 24 h: 12 delivered, 1 failed · the last one 2 h ago went through", "3 browsers")
    private static let load = row("load", "Processor load", .up, "1, 5 and 15 min load 0.42 · 0.37 · 0.30 on 8 cores of Docker's Linux VM", "0.42")
    private static let memory = row("memory", "Memory", .up, "3.1 GB of 7.7 GB in use on Docker's Linux VM · this site's process 312 MB", "40%")
    private static let disk = row("disk", "Disk", .up, "912 GB free of 1007 GB on Docker's virtual disk, which holds its containers and volumes", "912 GB free")
    private static let hostDisk = row("host-disk", "The PC's disk", .up, "131 GB free of 476 GB on the drive that holds the backups folder", "131 GB free")

    private static let internet = row("internet", "Internet", .up, "Cloudflare answered in 38 ms · public IP 203.0.113.7 · through Cloudflare AMM, JO", "38 ms")
    private static let dns = row("dns", "DNS", .up, "clients.neonjo.com → 104.21.32.1, 172.67.150.2 in 6 ms", "6 ms")
    private static let publicAddress = row("public", "Public address", .up, "clients.neonjo.com answered 200 in 412 ms, out through Cloudflare AMM and back in through the tunnel", "412 ms")
    private static let cameras = row("cameras", "Office cameras", .unknown, "Not set up: there is no cameras relay (neon-cameras) on this server")

    private static func report(server: [StatusRow], network: [StatusRow]) -> StatusReport {
        StatusReport(checkedAt: ISO8601DateFormatter().string(from: Date()), server: server, network: network)
    }

    /// Everything running; the cameras' relay not set up yet.
    static var healthy: StatusReport {
        report(
            server: [site, database, jobs, meetings, backups, whatsapp, apns, webPush, load, memory, disk, hostDisk],
            network: [internet, dns, publicAddress, cameras]
        )
    }

    /// Two things need attention: the ten-minute scheduler has gone quiet,
    /// and the PC's own drive is filling up.
    static var attention: StatusReport {
        report(
            server: [
                site, database,
                row("jobs", "Scheduled jobs", .degraded, "Last run 34 min ago (Thu, Oct 1 2:48 PM), took 2.1 s · expected every 10 minutes", "34 min ago"),
                meetings, backups, whatsapp, apns, webPush, load, memory, disk,
                row("host-disk", "The PC's disk", .degraded, "Running out: 8.4 GB free of 476 GB on the drive that holds the backups folder", "8.4 GB free"),
            ],
            network: [internet, dns, publicAddress, cameras]
        )
    }

    /// The tunnel is down: the site answers here, and nobody outside can reach it.
    static var tunnelDown: StatusReport {
        report(
            server: [
                site, database, jobs, meetings,
                row("backups", "Database backups", .unknown, "Not visible from the server: the backups folder is not mounted into the site's container"),
                row("whatsapp", "WhatsApp worker", .degraded, "The worker is running, but no number is linked · link it in Settings"),
                apns, webPush, load, memory, disk,
                row("host-disk", "The PC's disk", .unknown, "Not visible from the server: it is measured through the backups folder, which is not mounted"),
            ],
            network: [
                internet, dns,
                row("public", "Public address", .down, "Cloudflare answered 530: the tunnel (neon-tunnel) is not connected", "530"),
                cameras,
            ]
        )
    }
}
#endif
